### ISSUE TITLE
dataset download 

### ISSUE THREAD

**Issue by xumingzhang-2018** [Hsuxu/Two-branch-CNN-Multisource-RS-classification#1]
Hey,Can you share your dataset with me?
Looking  forward to your reply.

**Comment by Hsuxu** [comment]
[Houston](http://www.grss-ieee.org/community/technical-committees/data-fusion/2013-ieee-grss-data-fusion-contest/)
[Salinas,Pavia](http://www.ehu.eus/ccwintco/index.php?title=Hyperspectral_Remote_Sensing_Scenes)
[All Dataset](https://drive.google.com/drive/folders/1V_0MhD235rDI8Uo1BkzQujDlMxysTl3h?usp=sharing)

**Comment by xumingzhang-2018** [comment]
Thank you very much for your reply!

 But i also encountered the following problems：

1、But i don’t know how to get data like this ‘Salinas/Salinas_hsi.tif’ in your code 

LiDarName = 'Salinas_RGB.tif' # train hsi data

HsiName = 'Salinas_hsi.tif' # train lidar data

gth_train = 'Salinas_train.tif' # train data label

gth_test = 'Salinas_test.tif' # test data label

2、Can you share me the files in your logs folder? Like the following in your code.

_lidar_weights = "logs/weights/TRENTO_lidar_weights-0.8517.h5"

_hsi_weights = "logs/weights/TRENTO_hsi_weights-0.9535.h5"

_full_weights = "logs/weights/Hou_weights_finetune-0.8798.h5"

# save weightspip install pydot_ng

_weights_h = "logs/weights/TRENTO_hsi_weights.h5"

_weights_l = "logs/weights/TRENTO_lidar_weights.h5"

_weights = "logs/weights/Salinas_weights_"+str(2*r+1)+".h5"

'./logs/weights/models.h5'





------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2018年12月6日(星期四) 上午9:42
收件人: "Hsuxu/Two-branch-CNN-Multisource-RS-classification"<Two-branch-CNN-Multisource-RS-classification@noreply.github.com>; 
抄送: "☆"<1766380458@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Hsuxu/Two-branch-CNN-Multisource-RS-classification] dataset (#1)




Houston
 Salinas,Pavia
 All Dataset

**Comment by Hsuxu** [comment]
1. Please modify [lines](https://github.com/Hsuxu/Two-branch-CNN-Multisource-RS-classification/blob/master/data_util.py#L11-L23)
2. You can retrain the model to get same logs and checkpoits.

**Comment by Hsuxu** [comment]
closing
